### ISSUE TITLE
Add "New tab to right" menuitem

### ISSUE THREAD

**Issue by Gitoffthelawn** [Nidre/firefox-open-tabs-next-to-current-plus#1]
Would it be reasonable to add a tab context menuitem to open a new tab to the right of the selected tab?  (By selected tab, I am referring to the tab on which the context menu is evoked, not necessarily the currently open tab.)

**Comment by Ludomancer** [comment]
I was considering that too. But I've never had the time to implement such feature. I will definitely look into it If I find some time from my current projects.

**Comment by Gitoffthelawn** [comment]
Thanks!

**Comment by Ludomancer** [comment]
Discontinued in favor of [Open Tabs Next To Current]( https://github.com/sblask/firefox-open-tabs-next-to-current/ ) since all the functionality this fork was aimed for already implemented in the original add-on.
