### ISSUE TITLE
Minor Issue: Extension Homepage URL

### ISSUE THREAD

**Issue by Gitoffthelawn** [Nidre/firefox-open-tabs-next-to-current-plus#2]
The extension has https://github.com/Nidre/firefox-open-tabs-next-to-current listed as its homepage instead of https://github.com/Nidre/firefox-open-tabs-next-to-current-plus

Both URLs resolve to the same place, so it's not a problem, but you may want to update it since there is another extension with that name.

**Comment by Ludomancer** [comment]
I must've missed that detail :) Thanks for letting me now. Gonna push another version that will fix this issue. For now I'm just assigning it myself :)

**Comment by Gitoffthelawn** [comment]
You're welcome... I seem to be good at details lately!

**Comment by Ludomancer** [comment]
Discontinued in favor of [Open Tabs Next To Current]( https://github.com/sblask/firefox-open-tabs-next-to-current/ ) since all the functionality this fork was aimed for already implemented in the original add-on.
