### ISSUE TITLE
Update to reflect fixes in trunk extension

### ISSUE THREAD

**Issue by Gitoffthelawn** [Nidre/firefox-open-tabs-next-to-current-plus#3]
There was a bug report posted on AMO for the "Open Tabs Next to Current" extension (from where this extension was forked), and it received some patches.  If appropriate, can those patches be integrated into this extension?

**Comment by Ludomancer** [comment]
I will take a look into it as soon as I can. It might take a while tho.

**Comment by Gitoffthelawn** [comment]
Sounds good... thanks!

**Comment by Gitoffthelawn** [comment]
In addition to the above, you may also want to take a look at https://github.com/sblask/firefox-open-tabs-next-to-current/issues/7 and the fix for it.

**Comment by Ludomancer** [comment]
Discontinued in favor of [Open Tabs Next To Current]( https://github.com/sblask/firefox-open-tabs-next-to-current/ ) since all the functionality this fork was aimed for already implemented in the original add-on.
