### ISSUE TITLE
Affects closing of tabs: unintended consequence?

### ISSUE THREAD

**Issue by Gitoffthelawn** [Nidre/firefox-open-tabs-next-to-current-plus#4]
Using this extension affects which tab is selected when a tab is closed.  I'm not sure if that is by design or an unintended consequence.

**Comment by Ludomancer** [comment]
Hmm, could you elaborate a little more. 

What did you do?

What should have happened?

What happened?

Thanks :)

@Gitoffthelawn

**Comment by Gitoffthelawn** [comment]
Sure... I'll write up some details for you.  You mentioned that you are really busy right now, so let's keep this open, and I'll provide details soon.  If I get sidetracked, just ping me via this issue, and I'll get focused on it.

**Comment by Gitoffthelawn** [comment]
I think this is a direct consequence of Issue #5 ... a different definition of _new tab_.

**Comment by Ludomancer** [comment]
It might, I am not quite sure what this issue is, but if you think this was connected to the #5 and we have closed it, I think we can close this one too? @Gitoffthelawn

**Comment by Gitoffthelawn** [comment]
I think it's related... I'll close this.  Thanks!
